# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Руслан Курманалеев
email: ruslankurmanaleev@yandex.ru
description: >- # this means to ignore newlines until "baseurl:"
  Курманалеев Руслан - наставник и коуч айти-специалистов
baseurl: ""
url: ""
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
#  - jekyll-remote-theme
#  - jekyll-paginate
#  - jekyll-sitemap

date_format: "%B %-d, %Y"
timezone: "Europe/Moscow"
permalink: /:year-:month-:day-:title/
#paginate: 7

steve:
  archives: # Prefixes used with archive titles
    date: Posts from
    tag: More about…
    category: Posts filed in
  date_formats: # Uses <http://strftime.net>
    post: "%b %e, %Y" # The date format used in the post layout.
    archives: # The date formats for the archive layout.
      day: "%b %e, %Y"
      month: "%b, %Y"
      year: "%Y"
  page_404: |+
    The page you're looking for could not be found.

    Maybe the search can help.
  pagination: # Strings used in the blog- and post-pagination.
    next_page: "&laquo; Next"
    prev_page: "Previous &raquo;"
    prev_post: "Previous:"
    next_post: "Next:"
  post: # Strings used in the post layout.
    byline: "By"
    tags: More about…
  search: # Strings used in the search form.
    label: Search this blog
    placeholder: What you're looking for?
    submit: Go!

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - .idea/
