# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Руслан Курманалеев
email: ruslankurmanaleev@yandex.ru
description: >- # this means to ignore newlines until "baseurl:"
  Курманалеев Руслан - наставник и коуч айти-специалистов
baseurl: ""
url: ""
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-remote-theme
#  - jekyll-paginate
#  - jekyll-sitemap

date_format: "%B %-d, %Y"
timezone: "Europe/Moscow"
permalink: /:year-:month-:day-:title/
#paginate: 7

# Beautiful theme settings
#navbar-links:
#  Обо мне: "about"
#  Resources:
#    - Яндекс: "https://ya.ru"
#    - Learn markdown: "https://www.markdowntutorial.com/"
#  Мой сайт: "https://deanattali.com"
#avatar: "/assets/img/avatar-icon.png"
#round-avatar: true
#title-img: /path/to/image
social-network-links:
  vk: "https://vk.com"
  rss: true
  telegram: "@rumlarc"

share-links-active:
  vk: true
  twitter: false
  facebook: false
  linkedin: false

excerpt_length: 150
#feed_show_excerpt: true
#feed_show_tags: true
post_search: true
edit_page_button: false
# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
#navbar-var-length: false
#keywords: "my,list,of,keywords"

# colors:
#navbar-col: "#EAEAEA"
#navbar-text-col: "#404040"
#navbar-border-col: "#DDDDDD"
#page-col: "#FFFFFF"
#text-col: "#404040"
#link-col: "#008AFF"
#hover-col: "#0085A1"
#footer-col: "#EAEAEA"
#footer-text-col: "#777777"
#footer-link-col: "#404040"
#footer-hover-col: "#0085A1"
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

#site-css:
#  - "/assets/css/custom-styles.css"
#site-js:
#  - "/assets/js/custom-script.js"

# Tags:
#gtm: ""
#gtag: "G-XXXXXXXXXX"
#cloudflare_analytics: ""

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - .idea/
